version: '3.7'

networks:
  app-tier:
    driver: bridge

services:
  h2o:
    build: .
    container_name: h2o
    depends_on:
      - php-fpm
    ports:
      - 80:${HTTP_PORT}
      - 443:${HTTPS_PORT}
    env_file:
      .env
    volumes:
      - /containers/h2o:/etc/h2o
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/h2o:/var/log/h2o
      - /var/www:/var/www
    tmpfs: /tmp
    networks:
      - app-tier
    working_dir: /etc/h2o
    restart: always
    cap_add:
      - setuid
      - setgid
      - chown
      - sys_admin
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  php-fpm:
    image: php:7.4-fpm-alpine
    container_name: php-fpm
    volumes:
      - /var/www:/var/www
    networks:
      - app-tier
      